argocd:
  namespace: argocd
  labels: {}
spec:
  autoSync:
    selfHeal: true
    prune: true
  retry:
    limit: 5
    backoff:
      duration: "10s"
      factor: 2
      maxDuration: "3m"
  namePrefix: ""
  destination:
    name:
    namespace:
  source:
    repoURL:
    targetRevision:

applications: {}
