apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-root-infrastructure
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          # workaround for only specifying repo and revision once
          - list:
              elements:
                - repoUrl: http://git-repo-server.git-repo-server.svc.cluster.local:/git/manifests
                  baseName: infrastructure
                  role: infrastructure
          - git:
              repoURL: "{{.repoUrl}}"
              revision: "main"
              files:
                - path: composites/*/project.json
  template:
    metadata:
      name: 'composite-{{.path.basename | trimSuffix "-cluster"}}-{{.baseName}}'
    spec:
      project: default
      source:
        repoURL: "{{.repoUrl}}"
        targetRevision: "{{.revision}}"
        path: "{{.path.path}}"
        helm:
          valueFiles:
            - apps.yaml
          values: |
            composite-base:
              spec:
                namePrefix: {{.path.basename | trimSuffix "-cluster"}}-{{.baseName}}
                destination:
                  name: {{.destinationOverride | default (.path.basename | trimSuffix "-cluster")}}
                source:
                  repoURL: '{{.repoUrl}}'
                  targetRevision: {{.revision}}
      destination:
        name: 'in-cluster'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
          allowEmpty: false
        retry:
          limit: 5
          backoff:
            duration: "10s"
            factor: 2
            maxDuration: "3m"
