apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-demo
spec:
  # A Kafka cluster with three brokers and three Zookeeper nodes
  # We don't use resource requests and limits in this single node demo environment.
  # This kafka instance also does not configure an external listener.
  kafka:
    replicas: 3
    version: 3.8.0
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.8"
    storage:
      type: persistent-claim
      size: 1Gi

  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi

  entityOperator:
    topicOperator:
      watchedNamespace: kafka-demo
      reconciliationIntervalSeconds: 60
    userOperator:
      watchedNamespace: kafka-demo
      reconciliationIntervalSeconds: 60
